### ISSUE TITLE
Server will not start - Aborted (core dumped)

### ISSUE THREAD

**Issue by radinplaid** [mozilla/translation-service#23]
Hi!

I tried to give this server a try. I followed the instructions to build the Docker image which worked well, but then when I try to start the server, I get the following error:

``` 
docker run --name translation-service -it --rm -v $(pwd)/models:/models -p 8000:8000 -e LOGGING_LEVEL=DEBUG translation-service

Looking for models in "/models/uken"
Adding file trgvocab.uken.spm
Adding file srcvocab.uken.spm
Adding file model.uken.intgemm8.bin
Adding file lex.uken.s2t.bin
Building models config for uken
Aborted (core dumped)
```

I didn't see any errors in the console when building the docker image. I get the same error when I run the latest image from Docker hub `mozilla/translation-service`.

The problem seems to be the uken / enuk models - if I remove those folders from the model directory the server appears work well !

Probably this is fixed in PR #22 ?

**Comment by eu9ene** [comment]
Thanks for trying this! 

> Probably this is fixed in PR https://github.com/mozilla/translation-service/pull/22 ?

Yes, uk-xx models were not supported. It should be fixed now.
